name: Build and deploy ASP.Net Core apps to Azure

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # --- WEB API ---
      - name: Build WEB API
        run: dotnet build WebAPI/WebAPI.csproj --configuration Debug

      - name: Publish WEB API
        run: dotnet publish WebAPI/WebAPI.csproj \
              --configuration Debug \
              --output myapp

      # --- WEB APP ---
      - name: Build WebApp
        run: dotnet build WebApp/WebApp.csproj --configuration Debug

      - name: Publish WebApp
        run: dotnet publish WebApp/WebApp.csproj \
              --configuration Debug \
              --output myapp-webapp

      # --- Upload artifacts ---
      - name: Upload WEB API artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapi-artifact
          path: myapp

      - name: Upload WEB APP artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp-artifact
          path: myapp-webapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Descarga de artefactos en carpetas separadas
      - name: Download WEB API artifact
        uses: actions/download-artifact@v4
        with:
          name: webapi-artifact
          path: webapi

      - name: Download WEB APP artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp-artifact
          path: webapp

      # Autenticación en Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZUREAPPSERVICE_CLIENTID_C3DA96A9F73A43FC905DA70EC408261A }}
          tenant-id:       ${{ secrets.AZUREAPPSERVICE_TENANTID_47C25DA6CEB1427A8FBE3F9A27688994 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2DD758E6C6FE4EDA86F1B4A5001E5CD5 }}

      # Despliegue de la API al App Service correcto
      - name: Deploy WEB API to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cenfocinemas-jpastora'
          package:  webapi

      # Despliegue de la WebApp al App Service correcto
      - name: Deploy WebApp to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cenfocinemas-jpastora-webapp'
          package:  webapp
